# pylint: disable=pointless-statement

{
    "name": "OpenSPP - Grievance Redress Mechanism",
    "summary": "Provides a centralized Grievance Redress Mechanism for receiving, tracking, and resolving beneficiary complaints and feedback. It supports multi-channel submission, manages resolution workflows through customizable stages, and links grievances directly to individual or group registrants.",
    "version": "19.0.2.0.0",
    "sequence": 1,
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/OpenSPP2",
    "license": "LGPL-3",
    "development_status": "Production/Stable",
    "category": "OpenSPP/Monitoring",
    "external_dependencies": {"python": []},
    "maintainers": ["jeremi", "gonzalesedwin1123"],
    "depends": [
        "base",
        "mail",
        "portal",
        "spp_registry",
        "spp_area",
        "spp_user_roles",
        "spp_security",
    ],
    "data": [
        "data/grm_data.xml",
        "data/mail_alias.xml",
        "data/mail_templates.xml",
        "security/privileges.xml",
        "security/groups.xml",
        "security/grm_security.xml",
        "security/ir.model.access.csv",
        "security/rules.xml",
        "data/user_roles.xml",
        "views/res_partner_views.xml",
        "views/grm_ticket_menu.xml",
        "views/grm_ticket_stage_views.xml",
        "views/grm_ticket_category_views.xml",
        "views/grm_ticket_subcategory_views.xml",
        "views/grm_ticket_channel_views.xml",
        "views/grm_ticket_tag_views.xml",
        "views/grm_team_views.xml",
        "views/grm_sla_rule_views.xml",
        "views/grm_ticket_views.xml",
        "views/grm_portal_templates.xml",
    ],
    "assets": {},
    "demo": [],
    "images": [],
    "application": True,
    "installable": True,
    "auto_install": False,
}
