from . import test_vocabulary
from . import test_vocabulary_code
from . import test_vocabulary_mapping
from . import test_concept_group
from . import test_relationship_vocabulary
from . import test_deployment_profile
from . import test_access_rights
from . import test_system_vocabulary_protection
from . import test_e2e_workflow
