# pylint: disable=pointless-statement
{
    "name": "OpenSPP User Roles",
    "category": "OpenSPP",
    "version": "19.0.2.0.0",
    "sequence": 1,
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/OpenSPP2",
    "license": "LGPL-3",
    "development_status": "Production/Stable",
    "maintainers": ["jeremi", "gonzalesedwin1123"],
    "depends": [
        "base",
        "mail",
        "spp_registry",
        "base_user_role",
        "spp_security",
    ],
    "data": [
        "security/privileges.xml",
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/local_roles.xml",
        "data/global_roles.xml",
        "data/ir_cron.xml",
        "views/role.xml",
        "views/user.xml",
    ],
    "assets": {},
    "demo": [],
    "images": [],
    "application": False,
    "installable": True,
    "auto_install": ["spp_registry", "base_user_role"],
    "summary": "The OpenSPP User Roles module defines and manages distinct user roles, categorizing them as global or local, to implement area-based access control. It restricts user access to specific geographical areas by leveraging the spp_area module and automates underlying system permission assignments.",
}
