from . import grm_ticket
from . import grm_ticket_stage
from . import grm_ticket_tag
from . import grm_ticket_channel
from . import grm_ticket_category
from . import grm_ticket_subcategory
from . import grm_team
from . import grm_sla_rule
from . import res_partner
