# Part of OpenSPP. See LICENSE file for full copyright and licensing details.
"""Tests for RS256 token generation endpoint."""

import jwt

from odoo.tests import tagged

from .common import JWT_AUDIENCE, JWT_ISSUER, OAuthBridgeTestCase


@tagged("post_install", "-at_install")
class TestRS256TokenGeneration(OAuthBridgeTestCase):
    """Test the RS256 token generation function."""

    def test_generate_rs256_token(self):
        """Generated RS256 token has correct payload structure."""
        from ..routers.oauth_rs256 import _generate_rs256_jwt_token

        token = _generate_rs256_jwt_token(self.rsa_private_key_pem, self.api_client, 24)

        # Decode without verification to check payload structure
        payload = jwt.decode(
            token,
            self.rsa_public_key_pem,
            algorithms=["RS256"],
            audience=JWT_AUDIENCE,
            issuer=JWT_ISSUER,
        )

        self.assertEqual(payload["iss"], JWT_ISSUER)
        self.assertEqual(payload["sub"], self.api_client.client_id)
        self.assertEqual(payload["aud"], JWT_AUDIENCE)
        self.assertEqual(payload["client_id"], self.api_client.client_id)
        self.assertIn("exp", payload)
        self.assertIn("iat", payload)
        self.assertIsInstance(payload["scopes"], list)

    def test_generated_token_verifiable_by_bridge(self):
        """RS256 token generated by the endpoint can be verified by the bridge auth."""
        from ..middleware.auth_rs256 import _validate_rs256_token
        from ..routers.oauth_rs256 import _generate_rs256_jwt_token

        token = _generate_rs256_jwt_token(self.rsa_private_key_pem, self.api_client, 1)

        # Verify using the bridge's RS256 validation
        payload = _validate_rs256_token(self.env, token)
        self.assertEqual(payload["client_id"], self.api_client.client_id)

    def test_token_uses_rs256_algorithm(self):
        """Generated token uses RS256 algorithm in header."""
        from ..routers.oauth_rs256 import _generate_rs256_jwt_token

        token = _generate_rs256_jwt_token(self.rsa_private_key_pem, self.api_client, 24)

        header = jwt.get_unverified_header(token)
        self.assertEqual(header["alg"], "RS256")

    def test_token_payload_no_database_ids(self):
        """SECURITY: Generated RS256 token must not contain database IDs."""
        from ..routers.oauth_rs256 import _generate_rs256_jwt_token

        token = _generate_rs256_jwt_token(self.rsa_private_key_pem, self.api_client, 24)

        payload = jwt.decode(
            token,
            self.rsa_public_key_pem,
            algorithms=["RS256"],
            audience=JWT_AUDIENCE,
            issuer=JWT_ISSUER,
        )

        # Payload should not contain any database IDs
        self.assertNotIn("id", payload)
        self.assertNotIn("partner_id", payload)
        self.assertNotIn("db_id", payload)

    def test_token_lifetime_configurable(self):
        """Token lifetime is controlled by the hours parameter."""
        from ..routers.oauth_rs256 import _generate_rs256_jwt_token

        token_1h = _generate_rs256_jwt_token(self.rsa_private_key_pem, self.api_client, 1)
        token_48h = _generate_rs256_jwt_token(self.rsa_private_key_pem, self.api_client, 48)

        decode_kwargs = dict(algorithms=["RS256"], audience=JWT_AUDIENCE, issuer=JWT_ISSUER)
        payload_1h = jwt.decode(token_1h, self.rsa_public_key_pem, **decode_kwargs)
        payload_48h = jwt.decode(token_48h, self.rsa_public_key_pem, **decode_kwargs)

        # 48h token should expire much later than 1h token
        self.assertGreater(payload_48h["exp"], payload_1h["exp"])

    def test_token_scopes_from_client(self):
        """Token scopes match the API client's configured scopes."""
        from ..routers.oauth_rs256 import _generate_rs256_jwt_token

        token = _generate_rs256_jwt_token(self.rsa_private_key_pem, self.api_client, 24)

        payload = jwt.decode(
            token,
            self.rsa_public_key_pem,
            algorithms=["RS256"],
            audience=JWT_AUDIENCE,
            issuer=JWT_ISSUER,
        )

        expected_scopes = [f"{s.resource}:{s.action}" for s in self.api_client.scope_ids]
        self.assertEqual(payload["scopes"], expected_scopes)

    def test_missing_private_key_raises_clear_error(self):
        """Calling get_private_key when not configured raises OpenSPPOAuthJWTException."""
        from odoo.addons.spp_oauth.tools import OpenSPPOAuthJWTException, get_private_key

        # Clear private key
        self.env["ir.config_parameter"].sudo().set_param("spp_oauth.oauth_priv_key", False)

        with self.assertRaises(OpenSPPOAuthJWTException):
            get_private_key(self.env)

        # Restore for other tests
        self.env["ir.config_parameter"].sudo().set_param("spp_oauth.oauth_priv_key", self.rsa_private_key_pem)
