# Part of OpenSPP. See LICENSE file for full copyright and licensing details.
"""Tests for RS256 token generation endpoint."""

import asyncio

import jwt

from odoo.tests import tagged

from .common import JWT_AUDIENCE, JWT_ISSUER, OAuthBridgeTestCase


@tagged("post_install", "-at_install")
class TestRS256TokenGeneration(OAuthBridgeTestCase):
    """Test the RS256 token generation function."""

    def test_generate_rs256_token(self):
        """Generated RS256 token has correct payload structure."""
        from ..routers.oauth_rs256 import _generate_rs256_jwt_token

        token = _generate_rs256_jwt_token(self.rsa_private_key_pem, self.api_client, 24)

        # Decode without verification to check payload structure
        payload = jwt.decode(
            token,
            self.rsa_public_key_pem,
            algorithms=["RS256"],
            audience=JWT_AUDIENCE,
            issuer=JWT_ISSUER,
        )

        self.assertEqual(payload["iss"], JWT_ISSUER)
        self.assertEqual(payload["sub"], self.api_client.client_id)
        self.assertEqual(payload["aud"], JWT_AUDIENCE)
        self.assertEqual(payload["client_id"], self.api_client.client_id)
        self.assertIn("exp", payload)
        self.assertIn("iat", payload)
        self.assertIsInstance(payload["scopes"], list)

    def test_generated_token_verifiable_by_bridge(self):
        """RS256 token generated by the endpoint can be verified by the bridge auth."""
        from ..middleware.auth_rs256 import _validate_rs256_token_with_issuer
        from ..routers.oauth_rs256 import _generate_rs256_jwt_token

        token = _generate_rs256_jwt_token(self.rsa_private_key_pem, self.api_client, 1)

        # Verify using the bridge's RS256 validation
        payload, issuer_rec = _validate_rs256_token_with_issuer(self.env, token)
        self.assertEqual(payload["client_id"], self.api_client.client_id)
        self.assertFalse(issuer_rec, "internal-issuer token should return no issuer record")

    def test_token_uses_rs256_algorithm(self):
        """Generated token uses RS256 algorithm in header."""
        from ..routers.oauth_rs256 import _generate_rs256_jwt_token

        token = _generate_rs256_jwt_token(self.rsa_private_key_pem, self.api_client, 24)

        header = jwt.get_unverified_header(token)
        self.assertEqual(header["alg"], "RS256")

    def test_token_payload_no_database_ids(self):
        """SECURITY: Generated RS256 token must not contain database IDs."""
        from ..routers.oauth_rs256 import _generate_rs256_jwt_token

        token = _generate_rs256_jwt_token(self.rsa_private_key_pem, self.api_client, 24)

        payload = jwt.decode(
            token,
            self.rsa_public_key_pem,
            algorithms=["RS256"],
            audience=JWT_AUDIENCE,
            issuer=JWT_ISSUER,
        )

        # Payload should not contain any database IDs
        self.assertNotIn("id", payload)
        self.assertNotIn("partner_id", payload)
        self.assertNotIn("db_id", payload)

    def test_token_lifetime_configurable(self):
        """Token lifetime is controlled by the hours parameter."""
        from ..routers.oauth_rs256 import _generate_rs256_jwt_token

        token_1h = _generate_rs256_jwt_token(self.rsa_private_key_pem, self.api_client, 1)
        token_48h = _generate_rs256_jwt_token(self.rsa_private_key_pem, self.api_client, 48)

        decode_kwargs = dict(algorithms=["RS256"], audience=JWT_AUDIENCE, issuer=JWT_ISSUER)
        payload_1h = jwt.decode(token_1h, self.rsa_public_key_pem, **decode_kwargs)
        payload_48h = jwt.decode(token_48h, self.rsa_public_key_pem, **decode_kwargs)

        # 48h token should expire much later than 1h token
        self.assertGreater(payload_48h["exp"], payload_1h["exp"])

    def test_token_scopes_from_client(self):
        """Token scopes match the API client's configured scopes."""
        from ..routers.oauth_rs256 import _generate_rs256_jwt_token

        token = _generate_rs256_jwt_token(self.rsa_private_key_pem, self.api_client, 24)

        payload = jwt.decode(
            token,
            self.rsa_public_key_pem,
            algorithms=["RS256"],
            audience=JWT_AUDIENCE,
            issuer=JWT_ISSUER,
        )

        expected_scopes = [f"{s.resource}:{s.action}" for s in self.api_client.scope_ids]
        self.assertEqual(payload["scopes"], expected_scopes)

    def test_missing_private_key_raises_clear_error(self):
        """Calling get_private_key when not configured raises OpenSPPOAuthJWTException."""
        from odoo.addons.spp_oauth.tools import OpenSPPOAuthJWTException, get_private_key

        # Clear private key
        self.env["ir.config_parameter"].sudo().set_param("spp_oauth.oauth_private_key", False)
        self.addCleanup(
            self.env["ir.config_parameter"].sudo().set_param,
            "spp_oauth.oauth_private_key",
            self.rsa_private_key_pem,
        )

        with self.assertRaises(OpenSPPOAuthJWTException):
            get_private_key(self.env)


@tagged("post_install", "-at_install")
class TestRS256TokenEndpoint(OAuthBridgeTestCase):
    """Test the RS256 token endpoint function directly (not via HTTP).

    Calls the async get_rs256_token coroutine with constructed dependencies
    to test endpoint logic without needing a full FastAPI test client.
    """

    def _run_async(self, coro):
        """Run an async coroutine synchronously for testing."""
        return asyncio.run(coro)

    def _make_token_request(self, grant_type="client_credentials", client_id=None, client_secret=None):
        """Create a TokenRequest-like object for endpoint testing."""
        from odoo.addons.spp_api_v2.routers.oauth import TokenRequest

        return TokenRequest(
            grant_type=grant_type,
            client_id=client_id or self.api_client.client_id,
            client_secret=client_secret or self.api_client.client_secret,
        )

    def _make_mock_request(self):
        """Create a minimal mock HTTP request object."""

        class _MockRequest:
            def __init__(self):
                class _Client:
                    host = "127.0.0.1"

                self.client = _Client()

        return _MockRequest()

    def test_endpoint_valid_credentials(self):
        """RS256 endpoint returns valid token response with correct credentials."""
        from ..routers.oauth_rs256 import get_rs256_token

        token_request = self._make_token_request()
        response = self._run_async(get_rs256_token(self._make_mock_request(), token_request, self.env, None))

        self.assertEqual(response.token_type, "Bearer")
        self.assertIsNotNone(response.access_token)
        self.assertGreater(response.expires_in, 0)

        # Verify the returned token is valid RS256
        header = jwt.get_unverified_header(response.access_token)
        self.assertEqual(header["alg"], "RS256")

    def test_endpoint_invalid_grant_type(self):
        """RS256 endpoint rejects unsupported grant_type."""
        from fastapi import HTTPException

        from ..routers.oauth_rs256 import get_rs256_token

        token_request = self._make_token_request(grant_type="authorization_code")

        with self.assertRaises(HTTPException) as ctx:
            self._run_async(get_rs256_token(self._make_mock_request(), token_request, self.env, None))
        self.assertEqual(ctx.exception.status_code, 400)
        self.assertIn("grant_type", ctx.exception.detail.lower())

    def test_endpoint_invalid_credentials(self):
        """RS256 endpoint rejects invalid client credentials."""
        from fastapi import HTTPException

        from ..routers.oauth_rs256 import get_rs256_token

        token_request = self._make_token_request(client_secret="wrong-secret")

        with self.assertRaises(HTTPException) as ctx:
            self._run_async(get_rs256_token(self._make_mock_request(), token_request, self.env, None))
        self.assertEqual(ctx.exception.status_code, 401)

    def test_endpoint_missing_private_key(self):
        """RS256 endpoint returns 400 when RSA keys not configured."""
        from fastapi import HTTPException

        from ..routers.oauth_rs256 import get_rs256_token

        # Clear private key
        self.env["ir.config_parameter"].sudo().set_param("spp_oauth.oauth_private_key", False)
        self.addCleanup(
            self.env["ir.config_parameter"].sudo().set_param,
            "spp_oauth.oauth_private_key",
            self.rsa_private_key_pem,
        )

        token_request = self._make_token_request()

        with self.assertRaises(HTTPException) as ctx:
            self._run_async(get_rs256_token(self._make_mock_request(), token_request, self.env, None))
        self.assertEqual(ctx.exception.status_code, 400)
        self.assertIn("not available", ctx.exception.detail.lower())

    def test_endpoint_scope_string(self):
        """RS256 endpoint returns correct scope string from client scopes."""
        from ..routers.oauth_rs256 import get_rs256_token

        token_request = self._make_token_request()
        response = self._run_async(get_rs256_token(self._make_mock_request(), token_request, self.env, None))

        self.assertEqual(response.scope, "individual:read")
