# Part of OpenSPP. See LICENSE file for full copyright and licensing details.
{
    "name": "OpenSPP Farmer Registry: Vocabularies",
    "summary": "FAO-aligned vocabularies for farmer registry (crops, livestock, aquaculture)",
    "category": "OpenSPP",
    "version": "19.0.2.0.0",
    "sequence": 1,
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/OpenSPP2",
    "license": "LGPL-3",
    "development_status": "Production/Stable",
    "maintainers": ["jeremi", "gonzalesedwin1123", "emjay0921"],
    "depends": [
        "spp_vocabulary",
        "job_worker",
    ],
    "external_dependencies": {},
    "data": [
        "security/ir.model.access.csv",
        "data/vocab_farm_type.xml",
        "data/vocab_land_tenure.xml",
        "data/vocab_land_use.xml",
        "data/vocab_cultivation_method.xml",
        "data/vocab_activity_purpose.xml",
        "data/vocab_holder_type.xml",
        "data/vocab_data_source.xml",
        "data/vocab_irrigation_asset_type.xml",
        "data/vocab_crops_default.xml",
        "data/vocab_livestock_default.xml",
        "data/vocab_aquaculture_default.xml",
        "wizard/agrovoc_import_wizard_view.xml",
    ],
    "assets": {},
    "demo": [],
    "images": [],
    "application": False,
    "installable": True,
    "auto_install": False,
}
