{
    "name": "OpenSPP Statistics Dashboard",
    "summary": "Dashboard views for published statistics with area and program filtering.",
    "category": "OpenSPP/Monitoring",
    "version": "19.0.1.0.0",
    "sequence": 1,
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/OpenSPP2",
    "license": "LGPL-3",
    "development_status": "Alpha",
    "maintainers": ["jeremi"],
    "depends": [
        "spp_statistic",
        "spp_aggregation",
        "spp_area",
        "spp_programs",
        "spp_security",
        "queue_job",
    ],
    "data": [
        "security/privileges.xml",
        "security/groups.xml",
        "security/ir.model.access.csv",
        "data/ir_cron.xml",
        "views/dashboard_data_views.xml",
        "views/menus.xml",
    ],
    "assets": {},
    "demo": [],
    "images": [],
    "application": True,
    "installable": True,
    "auto_install": False,
}
