{
    "name": "OpenSPP HXL Integration",
    "summary": "Humanitarian Exchange Language (HXL) support for data interoperability. "
    "Adds HXL hashtag mapping to variables and export profiles for humanitarian coordination.",
    "category": "OpenSPP/Integration",
    "version": "19.0.2.0.0",
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/OpenSPP2",
    "license": "LGPL-3",
    "maintainers": ["jeremi", "gonzalesedwin1123", "emjay0921"],
    "development_status": "Beta",
    "depends": [
        "spp_security",
        "spp_cel_domain",
        "spp_studio",
        "spp_vocabulary",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/hxl_hashtags.xml",
        "data/hxl_attributes.xml",
        "views/hxl_tag_views.xml",
        "views/hxl_attribute_views.xml",
        "views/hxl_export_profile_views.xml",
        "views/cel_variable_views.xml",
        "views/menus.xml",
    ],
    "application": False,
    "installable": True,
    "auto_install": False,
}
