{
    "name": "OpenSPP QR Credentials",
    "summary": "MOSIP Claim 169 QR code identity credentials for registrants",
    "category": "OpenSPP/Identity",
    "version": "19.0.2.0.0",
    "sequence": 1,
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/OpenSPP2",
    "license": "LGPL-3",
    "development_status": "Beta",
    "maintainers": ["openspp-dev"],
    "depends": [
        "base",
        "mail",
        "spp_security",
        "spp_registry",
        "spp_key_management",
        "spp_audit",
        "spp_cel_domain",
    ],
    "external_dependencies": {
        "python": [
            "qrcode",
            "Pillow",
            "claim169",
            "jwcrypto",
        ],
    },
    "data": [
        "security/security_groups.xml",
        "security/ir.model.access.csv",
        "data/default_mappings.xml",
        "data/audit_rules.xml",
        "views/attribute_mapping_views.xml",
        "views/issuer_config_views.xml",
        "views/credential_views.xml",
        "views/res_partner_views.xml",
        "wizards/generate_qr_views.xml",
        "wizards/verify_qr_views.xml",
        "views/menu_views.xml",
    ],
    "assets": {},
    "demo": [],
    "images": [],
    "application": False,
    "installable": True,
    "auto_install": False,
}
