from . import test_bulk_consent
from . import test_consent_actions
from . import test_consent_edge_cases
from . import test_consent_history
from . import test_consent_immutability
from . import test_consent_matching
from . import test_consent_notice_integration
from . import test_consent_security_vulnerabilities
from . import test_consent_summary
from . import test_privacy_notices
from . import test_record_consent_wizard
from . import test_registrant
from . import test_security
