from . import scoring_model
from . import scoring_indicator
from . import scoring_value_mapping
from . import scoring_threshold
from . import scoring_invalid_value
from . import scoring_result
from . import scoring_result_detail
from . import scoring_engine
from . import scoring_batch_job
from . import scoring_indicator_provider
from . import scoring_data_integration
from . import res_partner
