{
    "name": "OpenSPP Change Request V2",
    "version": "19.0.2.0.0",
    "sequence": 50,
    "category": "OpenSPP",
    "summary": "Configuration-driven change request system with UX improvements, conflict detection and duplicate prevention",
    "author": "OpenSPP.org",
    "website": "https://docs.openspp.org",
    "license": "LGPL-3",
    "development_status": "Stable",
    "depends": [
        "base",
        "mail",
        "spp_base_common",
        "spp_registry",
        "spp_security",
        "spp_approval",
        "spp_event_data",
        "spp_dms",
        "spp_vocabulary",
    ],
    "data": [
        # Security
        "security/privileges.xml",
        "security/groups.xml",
        "security/rules.xml",
        "security/ir.model.access.csv",
        # Views (loaded before data that references them)
        "views/dms_file_views.xml",
        "views/change_request_type_views.xml",
        "views/change_request_views.xml",
        "views/detail_add_member_views.xml",
        "views/detail_edit_individual_views.xml",
        "views/detail_edit_group_views.xml",
        "views/detail_remove_member_views.xml",
        "views/detail_change_hoh_views.xml",
        "views/detail_exit_registrant_views.xml",
        "views/detail_transfer_member_views.xml",
        "views/detail_update_id_views.xml",
        "views/detail_create_group_views.xml",
        "views/detail_merge_registrants_views.xml",
        "views/detail_split_household_views.xml",
        "views/preview_changes_wizard_views.xml",
        "views/document_upload_wizard_views.xml",
        "views/conflict_rule_views.xml",
        "views/conflict_wizard_views.xml",
        "views/conflict_extensions.xml",
        # UX Improvements
        "views/create_wizard_views.xml",
        "views/batch_approval_wizard_views.xml",
        "views/conflict_comparison_wizard_views.xml",
        "views/queue_views.xml",
        "views/menus.xml",
        # Data
        "data/dms_directories.xml",
        "data/sequences.xml",
        "data/event_types.xml",
        "data/user_roles.xml",
        # Note: Default CR types are now provided by spp_cr_types_base and spp_cr_types_advanced
        # "data/default_types.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "spp_change_request_v2/static/src/components/**/*",
        ],
    },
    "installable": True,
    "application": False,
    "auto_install": False,
}
