# pylint: disable=pointless-statement
{
    "name": "OpenSPP Approval",
    "summary": "Standardized approval workflows with multi-tier sequencing and CEL rules",
    "version": "19.0.2.0.0",
    "license": "LGPL-3",
    "development_status": "Production/Stable",
    "author": "OpenSPP.org, OpenSPP Community",
    "website": "https://github.com/OpenSPP/OpenSPP2",
    "category": "OpenSPP",
    "depends": [
        "base",
        "mail",
        "spp_base_common",
        "spp_cel_domain",
        "spp_security",
    ],
    "data": [
        "security/privileges.xml",
        "security/groups.xml",
        "security/approval_security.xml",
        "security/ir.model.access.csv",
        "security/rules.xml",
        "data/mail_activity_types.xml",
        "data/approval_config_data.xml",
        "wizards/rejection_wizard_views.xml",
        "wizards/revision_wizard_views.xml",
        "views/approval_definition_views.xml",
        "views/approval_definition_views_multitier.xml",
        "views/approval_definition_views_cel.xml",
        "views/approval_tier_views.xml",
        "views/approval_review_views.xml",
        "views/approval_review_views_multitier.xml",
        "views/approval_freeze_views.xml",
        "views/menus.xml",
    ],
    "installable": True,
    "application": False,
    "maintainers": ["jeremi", "gonzalesedwin1123"],
}
