{  # pylint: disable=pointless-statement
    "name": "OpenSPP Attachment Antivirus Scan",
    "category": "OpenSPP",
    "version": "19.0.2.0.2",
    "sequence": 1,
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/OpenSPP2",
    "license": "LGPL-3",
    "development_status": "Beta",
    "maintainers": ["jeremi", "gonzalesedwin1123", "reichie020212", "emjay0921"],
    "depends": [
        "base",
        "mail",
        "job_worker",
        "spp_encryption",
        "spp_security",
    ],
    "external_dependencies": {
        "python": ["pyclamd"],
    },
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/av_scanner_data.xml",
        "data/quarantine_cron.xml",
        "views/av_scanner_backend_views.xml",
        "views/ir_attachment_views.xml",
    ],
    "assets": {},
    "demo": [],
    "images": [],
    "application": False,
    "installable": True,
    "auto_install": False,
}
